# Generated by Django 5.0.1 on 2024-02-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_adminprovince'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprovince',
            name='province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.province'),
        ),
    ]
