# Generated by Django 5.0.1 on 2024-02-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_adminprovince_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProvince',
        ),
    ]
