# Generated by Django 5.0.1 on 2024-02-01 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_adminprovince'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.province')),
            ],
        ),
    ]
