# Generated by Django 5.0.1 on 2024-02-06 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_provinceadmin'),
        ('project', '0003_delete_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('admin', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.company')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.officer')),
            ],
            options={
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
