# Generated by Django 5.0.1 on 2024-01-30 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('National', 'National'), ('Provincial', 'Provincial'), ('Local', 'Local')], max_length=100)),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100)),
                ('front_bw', models.FloatField(default=0.0)),
                ('front_color', models.FloatField(default=0.0)),
                ('inside_bw', models.FloatField(default=0.0)),
                ('inside_color', models.FloatField(default=0.0)),
                ('back_bw', models.FloatField(default=0.0)),
                ('back_color', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.district')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.province')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Advs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('size', models.FloatField()),
                ('caption', models.CharField(max_length=255)),
                ('adv_type', models.CharField(max_length=255)),
                ('balance', models.FloatField(default=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.company')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.newspaper')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('office', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='project.company')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.province'),
        ),
    ]
