# Generated by Django 5.0.1 on 2024-01-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('size', models.FloatField()),
                ('caption', models.CharField(max_length=255)),
                ('adv_type', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.company')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.newspaper')),
            ],
        ),
    ]
