# Generated by Django 5.0.1 on 2024-02-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
