# Generated by Django 5.0.1 on 2024-01-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_category_advs_balance_alter_company_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
