# Generated by Django 5.0.1 on 2024-01-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='type',
            field=models.CharField(choices=[('National', 'National'), ('Provincial', 'Provincial'), ('Local', 'Local')], max_length=100),
        ),
    ]
