# Generated by Django 5.0.1 on 2024-01-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_newspaper_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='back_bw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='back_color',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='front_bw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='front_color',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='inside_bw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='inside_color',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
