# Generated by Django 5.0.1 on 2024-01-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_newspaper_back_bw_alter_newspaper_back_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100),
        ),
    ]
