# Generated by Django 5.0.1 on 2024-01-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_newspaper_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advs',
            name='adv_type',
            field=models.CharField(max_length=255),
        ),
    ]
